services:

  mysql:
    image: mysql:8
    container_name: mysql-bookmyshow
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookmyshow
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  app:
    build: .
    container_name: bookmyshow-container
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8090:8080"
