version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-bookmyshow
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookmyshow
    ports:
      - "3306:3306"
    networks:
      - bookmyshow-net

  app:
    build: .
    container_name: bookmyshow-container
    depends_on:
      - mysql
    ports:
      - "8090:8080"
    networks:
      - bookmyshow-net

networks:
  bookmyshow-net:
